export interface NavItem {
  id: string;
  label: string;
  icon: string;
  children?: NavItem[];
}

export const navigationData: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: '⏱',
  },
  {
    id: 'master',
    label: 'Master',
    icon: '≡',
    children: [
      { id: 'role', label: 'Role', icon: '⊙' },
      { id: 'rights', label: 'Rights', icon: '⊙' },
      { id: 'users', label: 'Users', icon: '⊙' },
      { id: 'company-deduction', label: 'Company Deduction', icon: '⊙' },
    ],
  },
  {
    id: 'company',
    label: 'Company',
    icon: '≡',
    children: [
      { id: 'financial-year', label: 'Financial Year', icon: '⊙' },
      { id: 'company-kyc', label: 'Company KYC', icon: '⊙' },
      { id: 'country', label: 'Country', icon: '⊙' },
      { id: 'state', label: 'State', icon: '⊙' },
      { id: 'gst-state', label: 'GST State', icon: '⊙' },
      { id: 'district', label: 'District', icon: '⊙' },
      { id: 'field-area', label: 'Field Area', icon: '⊙' },
      { id: 'professional-tax', label: 'Professional Tax', icon: '⊙' },
      { id: 'lwf', label: 'LWF', icon: '⊙' },
      { id: 'user-pending-approval', label: 'User Pending Approval', icon: '⊙' },
      { id: 'user-permission-map', label: 'User Permission Map', icon: '⊙' },
      { id: 'region', label: 'Region', icon: '⊙' },
      { id: 'enclosure', label: 'Enclosure', icon: '⊙' },
      { id: 'client-vertical', label: 'Client Vertical', icon: '⊙' },
      { id: 'company-banks', label: 'Company Banks', icon: '⊙' },
      { id: 'client-services', label: 'Client Services', icon: '⊙' },
      { id: 'esic-code', label: 'ESIC Code', icon: '⊙' },
      { id: 'pf-code', label: 'PF Code', icon: '⊙' },
      { id: 'payroll-open-month', label: 'Payroll Open Month', icon: '⊙' },
    ],
  },
  {
    id: 'vendor',
    label: 'Vendor',
    icon: '≡',
    children: [
      { id: 'master-vendor', label: 'Master Vendor', icon: '⊙' },
      { id: 'master-payment', label: 'Master Payment', icon: '⊙' },
      { id: 'report-vendor-payment', label: 'Report Vendor Payment', icon: '⊙' },
    ],
  },
  {
    id: 'client',
    label: 'Client',
    icon: '≡',
    children: [
      { id: 'state-office', label: 'State Office', icon: '⊙' },
      { id: 'zone', label: 'Zone', icon: '⊙' },
      { id: 'shift', label: 'Shift', icon: '⊙' },
      { id: 'services', label: 'Services', icon: '⊙' },
      { id: 'client-category', label: 'Client Category', icon: '⊙' },
      { id: 'nature-of-services', label: 'Nature of Services', icon: '⊙' },
      { id: 'client-master', label: 'Client', icon: '⊙' },
      { id: 'unit', label: 'Unit', icon: '⊙' },
      { id: 'report-client', label: 'Report Client', icon: '⊙' },
      { id: 'report-unit', label: 'Report Unit', icon: '⊙' },
      { id: 'salary-rate-breakup', label: 'Salary Rate Break Up', icon: '⊙' },
      { id: 'bill-rate-breakup', label: 'Bill Rate Break Up', icon: '⊙' },
      { id: 'report-bill-rate-break', label: 'Report Bill Rate Break Up', icon: '⊙' },
      { id: 'report-salary-rate-break', label: 'Report Salary Rate Break Up', icon: '⊙' },
      { id: 'contract-details', label: 'Contract Details', icon: '⊙' },
    ],
  },
  {
    id: 'employee',
    label: 'Employee',
    icon: '≡',
    children: [
      { id: 'qualification', label: 'Qualification', icon: '⊙' },
      { id: 'additional-qualification', label: 'Additional Qualification', icon: '⊙' },
      { id: 'bank', label: 'Bank', icon: '⊙' },
      { id: 'employee-grade', label: 'Employee Grade', icon: '⊙' },
      { id: 'update-employee-field', label: 'Update Employee Field', icon: '⊙' },
      { id: 'new-employee', label: 'New Employee', icon: '⊙' },
      { id: 'edit-person-detail', label: 'Edit Person Detail', icon: '⊙' },
      { id: 'edit-communication', label: 'Edit Communication', icon: '⊙' },
      { id: 'edit-police-verification', label: 'Edit Police Verification', icon: '⊙' },
      { id: 'edit-exservice-details', label: 'Edit ExService Details', icon: '⊙' },
      { id: 'edit-gunman-details', label: 'Edit Gunman Details', icon: '⊙' },
      { id: 'edit-training', label: 'Edit Training', icon: '⊙' },
      { id: 'edit-medical', label: 'Edit Medical', icon: '⊙' },
      { id: 'edit-employee-family', label: 'Edit Employee Family', icon: '⊙' },
      { id: 'edit-employee-left', label: 'Edit Employee Left', icon: '⊙' },
      { id: 'employee-rejoin', label: 'Employee Rejoin', icon: '⊙' },
      { id: 'employee-salary-break', label: 'Employee Salary Breakup', icon: '⊙' },
      { id: 'waiting-for-placement', label: 'Waiting for Placement', icon: '⊙' },
      { id: 'report-employee', label: 'Report Employee', icon: '⊙' },
      { id: 'report-police-verification', label: 'Report Police Verification', icon: '⊙' },
    ],
  },
  {
    id: 'admin-utility',
    label: 'Admin/Utility',
    icon: '≡',
  },
  {
    id: 'payroll',
    label: 'Payroll',
    icon: '≡',
    children: [
      { id: 'monthly-attendance', label: 'Monthly Attendance', icon: '⊙' },
      { id: 'delete-attendance', label: 'Delete Attendance', icon: '⊙' },
      { id: 'create-salary', label: 'Create Salary', icon: '⊙' },
      { id: 'approve-attendance', label: 'Approve Attendance', icon: '⊙' },
      { id: 'delete-salary', label: 'Delete Salary', icon: '⊙' },
      { id: 'salary-process', label: 'Salary Process', icon: '⊙' },
      { id: 'report-employee-salary', label: 'Report Employee Salary', icon: '⊙' },
      { id: 'report-emp-history', label: 'Report Employee History', icon: '⊙' },
      { id: 'bank-transfer', label: 'Bank Transfer', icon: '⊙' },
      { id: 'monthly-attendance-note', label: 'Monthly Attendance Note', icon: '⊙' },
      { id: 'report-attendance-summary', label: 'Report Attendance Summary', icon: '⊙' },
      { id: 'attendance-checklist', label: 'Attendance Checklist', icon: '⊙' },
      { id: 'report-pf', label: 'Report PF', icon: '⊙' },
      { id: 'report-esi', label: 'Report ESI', icon: '⊙' },
      { id: 'report-deduction-to-bank', label: 'Report Deduction To Bank', icon: '⊙' },
      { id: 'report-shortage', label: 'Report Shortage', icon: '⊙' },
      { id: 'pay-register', label: 'Pay Register', icon: '⊙' },
    ],
  },
  {
    id: 'billing',
    label: 'Billing',
    icon: '≡',
    children: [
      { id: 'recent-entry', label: 'Recent Entry', icon: '⊙' },
      { id: 'report-ppu', label: 'Report PPU', icon: '⊙' },
      { id: 'generate-invoice', label: 'Generate Invoice', icon: '⊙' },
      { id: 'report-gst-invoice', label: 'Report GST Invoice', icon: '⊙' },
      { id: 'update-duplicate-bills', label: 'Update Duplicate Bills', icon: '⊙' },
      { id: 'edit-invoice', label: 'Edit Invoice', icon: '⊙' },
      { id: 'report-client-ledger', label: 'Report Client Ledger', icon: '⊙' },
    ],
  },
  {
    id: 'advance-module',
    label: 'Advance Module',
    icon: '≡',
  },
  {
    id: 'bill-report',
    label: 'Bill Report',
    icon: '≡',
    children: [
      { id: 'report-gstri', label: 'Report GSTRI', icon: '⊙' },
      { id: 'report-duty-diff-bill', label: 'Report Duty Diff Bill', icon: '⊙' },
    ],
  },
  {
    id: 'utilities',
    label: 'Utilities',
    icon: '≡',
  },
  {
    id: 'app-report',
    label: 'App Report',
    icon: '≡',
  },
  {
    id: 'mis',
    label: 'MIS',
    icon: '≡',
  },
];
